### ISSUE TITLE
make csg substract only use caulk

### ISSUE THREAD

**Issue by thunderpwn** [TTimo/GtkRadiant#257]
I wish you guys could make this happend, I know its better to substract with a caulked brush but even then sometimes it makes trouble with terrain.
I get terrain texture underneath or on sides not visible sometimes.
Would be great if it Just used caulk...
Dont know if this is posssible though
but away from that great job guys!

**Comment by thunderpwn** [comment]
Would like an answear here guys :D , is this possible? is it gonna happen at all?

**Comment by thunderpwn** [comment]
any news on this one?

**Comment by TTimo** [comment]
patches welcome, I marked this 1.6.5 so there's more chances of it being looked at

**Comment by TTimo** [comment]
This would take a little bit of real dev work - anyone want to take it on?

**Comment by thunderpwn** [comment]
wish I could, but I am hopeless with code :/

**Comment by TTimo** [comment]
I'm looking at the CSG operations. I see 4 of them:
- Make Hollow Overlap
- Make Hollow Touch
- CSG Substract
- CSG Merge

Merge never creates new surfaces, so this doesn't apply.

Make Hollow Overlap/Touch, I think you should set the texture to caulk or something else before applying the operation, and you'll get a textured or caulk result, nothing particular is needed there.

For CSG Substract, it seems to me that if you CSG Substract with a caulk brush, then all new splits should have the caulk surface. Otherwise you CSG Substract with a textured brush and the new splits will use whatever shader from the brush they are cut from.

This seems like the way to go for me, or am I missing something?

**Comment by TTimo** [comment]
Or maybe hollow overlap/touch does need a preference setting too, where you would still keep the original faces whatever they were and still control the new splits becoming caulk or not.

**Comment by TTimo** [comment]
Will be in next build.

**Comment by thunderpwn** [comment]
great news 👍
