### ISSUE TITLE
entities.def parser: entity flags

### ISSUE THREAD

**Issue by neumond** [TTimo/GtkRadiant#262]
If the line is
```/*QUAKED entityname (color) (pos) (pos) FLAG1 FLAG2 FLAG3```
everything is OK, but if
```/*QUAKED entityname (color) FLAG1 FLAG2 FLAG3```
first flag ignored.
Different entities.def files solves that by placing here something as "?". For ex.:
```/*QUAKED func_bobbing (0 .5 .8) ? X_AXIS Y_AXIS```

Firstly I thinked "?" has some special meaning, like "-". But string
```/*QUAKED func_bobbing (0 .5 .8) ? ? ? X_AXIS Y_AXIS```
makes last 2 "?" appear in editor.

According to source - this is just a mistake. Token read for matching "(", but reading position not reverted back. Instead of "?" you can write here "ABIG_POEMIN_ONELINE_WITHOUTSPACES" - it would be also ignored.

It's not so hard to patch, but it can break some existing .def files.
If it's not gonna be fixed, maybe put this issue at least in docs (I still didn't found the doc on entities.def).

**Comment by ericwa** [comment]
Hmm, not a fan of this, because it breaks old .def files floating around (e.g. for mods).

According to the GTKR 1.5 source, the ? after the color is supposed to indicate that there is no specific bounding box:
https://github.com/TTimo/GtkRadiant/blob/1.5/radiant/eclass_def.cpp#L198

Seems that ? is also used in the list of spawnflags as a placeholder for an unused spawnflag, e..g:
https://github.com/jdolan/quetoo/blob/a66ea8286ef0c037536f061f4a0f93715fa52f55/src/game/default/g_entity_misc.c#L78

So my understanding is, in `/*QUAKED func_bobbing (0 .5 .8) ? ? ? X_AXIS Y_AXIS` , the first ? means no bounding box, the next two mean to skip spawnflags 1 and 2.

Does the `/*QUAKED entityname (color) FLAG1 FLAG2 FLAG3` format show up in the wild?
