### ISSUE TITLE
Remove QuakeLive encrypted pk3 support

### ISSUE THREAD

**Issue by ensiform** [TTimo/GtkRadiant#451]
QL doesn't use encrypted PK3s anymore since the switch to Steam F2P afaik possibly even before that.

**Comment by illwieckz** [comment]
I can't tell the pk3 status for current steam's quakelive since I haven't bought it, but my installation dir for the previous free to play standalone quakelive is full of unencrypted pk3 when the installation dir from my previous free to play web browser quakelive plugin dir is full of encrypted ones.

So, based on files I have, the encryption status is:

- crossplatform web plugin quakelive: encrypted
- windows standalone quakelive: unencrypted
- steam windows standalone quakelive: unknown

I can't tell for that steam release since it was never free to play on steam, but I think we would have heard it if encryption was reactivated, no?

**Comment by ensiform** [comment]
They switched to unencrypted since windows standalone. the steam version is the same just wrapped in steam pretty much.

**Comment by illwieckz** [comment]
yes, and I've just verified than pk3s shipped with steamapp 349090 (quakelive dedicated server) are not encrypted either.

**Comment by Pan7** [comment]
This should be done:
Edit gamepack file QLPack\game\synapse.config and replace the VFS qlpk3 with pk3.
Remove the plugin in plugins\vfsqlpk3 from Radiant.

**Comment by TTimo** [comment]
Done (next build).
