### ISSUE TITLE
Refactor fixedWinding_t to use flexible array

### ISSUE THREAD

**Issue by TTimo** [TTimo/GtkRadiant#583]

**Comment by tkoeppe** [comment]
This ought to be straight-forward; we should just look for any uses of `MAX_POINTS_ON_FIXED_WINDING`, and make sure that there isn't some intentional use as automatic variables of that type.

**Comment by tkoeppe** [comment]
Note to self:

   * Change `fixedWinding_t` in q3map2.h
   * Update vis.c and visflow.c; remove branching and use `sizeof`

**Comment by tkoeppe** [comment]
The `fixedWinding_t` type is used as a fixed-length type in the `pstack_t` structure, here: https://github.com/TTimo/GtkRadiant/blob/master/tools/quake3/q3map2/q3map2.h#L1238

That type in turn is used as an automatic variable in several places.

This means it cannot change the array to a flexible array, since the static capacity is actually used. I think I'll just revert the offset code in vis.c and visflow.c, even though the situation isn't entirely satisfactory. But I also can't think of a better solution that doesn't require larger changes in the way the `pstack_t` structure is used.

**Comment by TTimo** [comment]
Oh, I guess I should have taken the hint about 'fixed' in fixedWinding_t ..
you are contributor now, so feel free to check this in directly.

**Comment by tkoeppe** [comment]
Yep, will do!
